name: Secret Scanning with Gitleaks

on:
  push:
    branches:
      - main  # This will trigger the action on every push to the 'main' branch.

jobs:
  scan:
    runs-on: ubuntu-latest  # This specifies the runner environment.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out the code in the repository.

    - name: Set up Gitleaks
      run: |
        # Install Gitleaks
        curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.0.0/gitleaks-linux-amd64.tar.gz | tar xz -C /usr/local/bin

    - name: Run Gitleaks to scan for secrets
      run: |
        gitleaks detect --source=./ --report=./gitleaks-report.json
      continue-on-error: true  # Continue even if secrets are found (optional).

    - name: Upload Gitleaks Report
      uses: actions/upload-artifact@v2
      with:
        name: gitleaks-report
        path: ./gitleaks-report.json
